### ISSUE TITLE
how to aggregate NA in upstream attribute aggregation?

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/delaware-model-prep#10]
Some of the catchment attributes have categorical values for the attribute. So we need to figure out how to deal with that since a mean or sum is meaningless. Here are those variables:
|variable| description|
|---|---|
|soil_type|	Soil type designation.Texture is first designated for each cell in the input raster map of soils data. 3 is assigned if clay content exceeds 40 percent. 1 is then assigned to any cell with less than 40% clay but more than 50% sand content. The remaining cells are assinged a code of 2. soil_type for the feature indicates the most commonly occuring (per-cell) soil type.	|
|cov_type|	Land cover type designation.  Cover type is first designated for each cell in the input raster map of land cover data. This is done by reclassifying the input land cover raster data set. As a quality assurance measure, any cells whose elevation exceeds timberline (set to 11,500 ft) and have shrub or tree designations are reset to grass (code 2). cov_type is set to 0 for a feature if the cover type cells within the feature aremore than 90% bare. If move than 20% of the feature is covered by tree cells, then cov_type is set to 3. For features that are unassigned a cov_type value by the preceding, a code of 2 is assigned to any feature with more than 20% shrub cover. Features that are still unassigned but with a combination of shrub and tree cover that exceeds 35% are then assigned a value. cov_type code 3 is assigned to features within this set with more tree than shrub area, with the remainder being assigned a value of 2. Any features still not designated with a cov_type are assigned according to the more commonly occuring (per-cell) cov_type within the feature. The final step is to re-assign the cov_type for any feature whose hru_elev value exceeds timberline (11,500 feet) and whose cov_type value is 2 or 3 to 1.	|
|rad_trncf|	Radiation transmission coefficient. A per-cell surface indicating the winter vegetation density where the cov_type value is 3 ("tree") is created. The winter vegetation density is the summer vegetation density reduced by a "leaf keep" factor based on the prms cov_type. The following list shows pairings of cov_type and the percent of summer vegetation density to maintain. [[0, 0], [1, 80], [2, 70], [3, 60], [4, 100]].	|
|hru_deplcrv|	Snow depletion curve number, an identifier, corresponds to one of two empically derived curves. For features with  hru_elev exceeding timber line, which is set at 11,500 feet above sea level, curve number 2 is designated. All other features are assigned to curve number 1.	|
|dprst_flow_coef|	Depression storage seepage rate. Initially set to equal the slowcoef_lin value. Values for all features are then linearly scaled to fit within a range (specified below) .	|

**Comment by jsadler2** [comment]
Options:
1. Leave them out
2. Choose the one at the outlet
3. Choose the one that is most represented in the catchment by area
4. ...

**Comment by aappling-usgs** [comment]
I like option 3. But are you sure that rad_trncf and dprst_flow_coef are categorical?

**Comment by jsadler2** [comment]
> are you sure that rad_trncf and dprst_flow_coef are categorical?

No. ha. I will check.

**Comment by jsadler2** [comment]
Looks like you are right, @aappling-usgs they are not categories. They just don't have a unit, but I think since they are _coefficients_ it would be meaningful to average them.

**Comment by jsadler2** [comment]
> Choose the one that is most represented in the catchment by area

Yeah I think that makes most sense. I will need to go further upstream b/c I was averaging these attributes between the (usually 2) hru's to assign to each stream segment.

**Comment by jsadler2** [comment]
So I'll be doing number 3 for `soil_type`, `cov_type`, and `hru_deplcrv`
