### ISSUE TITLE
realsat indicators not committed 

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/delaware-model-prep#101]
I went to build the drb-temp-data-release today and I could not `gd_get` file `2_observations/out/reservoir_realsat_monthly_surface_area.csv,ind` because the indicator does not exist (but the [file does in GD](https://drive.google.com/drive/folders/1jR-BkDMEnxsiFXUAqO_VmR0d52DpcdvH)). @hcorson-dosch - can you see if you have some indicators hanging out that need to be committed? Or run an `scmake()` on that indicator? I suspect you forgot to do that after changes Alison requested [in this PR](https://github.com/USGS-R/delaware-model-prep/pull/90/files). I would build myself but looked like the monthly data file extraction was going to take hours.

**Comment by hcorson-dosch** [comment]
Whoops --- sorry about that, Sam. Yes, I forgot to commit the two realsat indicator files. Just did so and will tag you in the PR.
