### ISSUE TITLE
Change in # obs included in in `9_collaborator_data/res/res_io_obs.feather`?

### ISSUE THREAD

**Issue by hcorson-dosch** [USGS-R/delaware-model-prep#106]
While updating the file names and re-testing the data prep code in the `res-temperature-process-models` repo to reflect changes made to file types in the `drb-temp-data-release` SB, I noticed that the reservoir inflow outflow observation csv (`reservoir_io_obs.csv`, sourced from `delaware-model-prep/9_collaborator_data/res/res_io_obs.feather`) currently has 52,971 observations and no rows where 'location' == 'inflow', when previoulsy the file had 203,981 observations and values of 'outflow' and 'inflow' for 'location'

**Comment by limnoliver** [comment]
I've narrowed it to the target `res_inflow_ids` which uses NLDI to find inflow sites, and is returned empty for me. I made sure I had the latest version of `dataRetrieval` and built it again, but it's still empty. Will follow up more tomorrow.

**Comment by limnoliver** [comment]
@aappling-usgs -- could you rebuild `res_inflow_ids` and see what you get? If you get a non-empty list, maybe commit or cache this object so we don't have to rebuild? Currently, everyone has to build it, and I bet most will miss that you need the latest version of `dataRetrieval`.

You could PR my open PR [here](https://github.com/USGS-R/delaware-model-prep/pull/107) as I've not yet merged changes after the data release review.

**Comment by hcorson-dosch** [comment]
Sam's fix is in #107, [here](https://github.com/USGS-R/delaware-model-prep/pull/107/commits/16af07cb6bdd5fb7b6cbbb9de07ea8fc2bf6504b)
