### ISSUE TITLE
Some tributary monitoring sites being matched to the main stem

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/delaware-model-prep#113]
From Janet: 

> As an aside, I found a couple weird observation sites on reach 1637 (west branch of the neversink). Sites USGS−01434097 (USGS 01434097 HEMLOCK BK AT LOGGING RD NR FROST VALLEY NY) and USGS−415828074310701 (USGS 415828074310701 TRIB TO W BR NEVERSINK RIVER, TSTAX0001) are among the obs sites, but they are listed as being on tributaries in NWIS.

**Comment by lekoenig** [comment]
Thanks, Janet! I took a look at these sites and agree that they are located on tributary streams and should not be matched to segment 1637 in the NHM network. I'll flag these sites accordingly. 

USGS-01434097 and USGS-415828074310701 are ~93 and 49 m away from the mainstem river, respectively, highlighting that there is no "right" cutoff (maximum bird distance) for deciding to match a lat/lon to a nearby river segment. I'm working on some checks/flags that will hopefully reduce the number of trib sites getting matched to mainstem rivers, but more eyes on the data always helps ✨

**Comment by lekoenig** [comment]
Both of the sites Janet flagged above (USGS−01434097 and USGS−415828074310701) should have been addressed in #119 (and now recommended for "drop" in `2_observations/in/drb_filtered_sites_seg_match_QC.csv`. OK to close this issue?
