### ISSUE TITLE
Mismatch in adjacency matrix/ sntemp output full DRB

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/delaware-model-prep#19]
There is a mismatch in the number of segments in the adjacency matrix and the sntemp output for the full DRB.

The adjacency matrix (i.e. updown.npy in the UMN-USGS Data Sharing/Streams GCN/Full Network/NN Inputs/dists_full.npz) is 459 x 459.

In the sntemp_input_output.feather (from the same GDrive folder), there are 456 segments.

(This was originally an issue in my ML model repo, so I will transfer comments from there.)

**Comment by jsadler2** [comment]
From @aappling-usgs:
> Ugh, that's no good. I suspect that dists_full.npz is built from the original network whereas sntemp_input_output.feather reflects the revised network where I corrected a few weird segments and connections. 456 x 456 would be better matrix dimensions. There's probably something to fix in https://github.com/aappling-usgs/delaware-model-prep/blob/master/9_collaborator_data.yml or related files...

**Comment by jsadler2** [comment]
I think `NA`'s may be to blame. When I look at the `1_network/out/network.rds`, there are 3 rows with `NA` for `seg_id_nat`:

```R
> n = readRDS('1_network/out/network.rds')
> sum(is.na(n$edges$seg_id_nat))
[1] 3
```

**Comment by jsadler2** [comment]
So I guess that means we need to somehow get rid of the 3 rows/columns in the adjacency matrix that correspond to the `NA`'s?

**Comment by jzwart** [comment]
The 456 segments are from the fabric cutout that Markstrom gave us. I thought @aappling-usgs had added some segments to make connections to segments that were not connected to the rest of the network (maybe flowing into the estuary). But maybe I'm remembering that incorrectly

**Comment by aappling-usgs** [comment]
Ohhhhhh. Golly. Yes, Jake, that's exactly right and I feel like a fool - of course SNTemp outputs wouldn't line up with a corrected network! So now the question is what is the best choice for a PGDL model for the whole basin: do we revert to the uncorrected network, or do we leave out or construct SNTemp predictions for the segments I added?

**Comment by jzwart** [comment]
Hmm... I think it would take more time to construct SNTemp predictions for the new segments since we would have to create new HRU's connecting those segments and parameterize those HRU's and segments. Without knowing how this gets done with the regular NHM fabric, I think it would be difficult for us to complete quickly. Do we know where the new corrected segments are? If they are the ones connecting to the estuary, then we could just cut them out since they don't have very many obs. (see red circle below) 
![image](https://user-images.githubusercontent.com/4825431/77767304-3c830680-7017-11ea-8ec0-79161e97785d.png)

**Comment by aappling-usgs** [comment]
I think there are two in the northeastern corner and one somewhere near Trenton. When I wrote "construct" I was thinking of something simpler than rerunning SNTemp, more like interpolation. But even that would be challenging and questionable, so I'm leaning toward just omitting SNTemp predictions for the new or split reaches and using a mask when calculating the loss.

This also raises questions about how useful the network corrections are. I'll dig them up and share shortly to get your thoughts on whether we should just use the original network.

**Comment by jsadler2** [comment]
So does that explain the `NA`'s in `seg_nat_id` column in the `network.rds` file? Those three segments don't have `seg_nat_id`'s b/c Alison created them?

**Comment by aappling-usgs** [comment]
Yep, that's why. I should have caught this way earlier! Thank goodness for Jake.

**Comment by jsadler2** [comment]
Alison and I talked about this this morning. Two of the "new" segments come from this spot:
<img width="383" alt="Annotation 2020-03-27 132353" src="https://user-images.githubusercontent.com/6943441/77787943-68f64d00-702e-11ea-86f7-3aa49798fb9e.png">
For the sake of the distance matrix calculation, segments 3 and 8 get split since the upstream segment intersects in the middle of the segment. 

To resolve, we thought it best to 
1. use the sntemp input outputs for the entire segment (as is currently in our dataset)
2. recalculate the distance matrix keeping only the distances from the lower part of the segment. This way the number of segments should be the same in the distance matrix and the sntemp data. In doing this we will need to exclude the distance to "skip" the upstream half of the split segments in the matrix calculation. 

Did I get this right, @aappling-usgs ?

**Comment by aappling-usgs** [comment]
I agree with the one modification that for (2), I think we want to _calculate_ the distance matrix using the corrected network (the one with both 3_1 and 3_2) so that there's a finite distance between segments 3_1 and 1. and then we can _subset_ the distance matrix to leave out the rows and columns containing the three upstream subsegments (3_2, 8_2, and 50_2).

**Comment by jsadler2** [comment]
Ah. Yes. That is much cleaner/easier.
