### ISSUE TITLE
Find and retrieve all NGWOS data

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/delaware-model-prep#29]
After Alison's presentation, Brian Pellerin noted it didn't look like we had all NGWOS data. He sent a [spreadsheet of sites](https://drive.google.com/drive/folders/1vr7xNHquiIczosTdl4MMJ2xRB3mr9Gdl), and noted that we should pay attention to those sites with an "x" in the "Temp" column. We should use this spreadsheet to pull NGWOS data in the future.

**Comment by limnoliver** [comment]
Some follow up notes here:

- There were 98 sites with x's in the "Temp" column in Brian's spreadsheet, indicating 98 new DRB temperature sites.

- 95/98 temperature sites had site IDs assigned, the rest were listed as TBD.

- A few sites had duplicated rows, so the final tally of searchable sites from Brian's NGWOS spreadsheet was 91 sites. 

- NWIS found (e.g., by using `dataRetrieval::readNWISsite`) 91/91 of these sites. 

- 5/91 sites were not stream sites (3 lakes, 1 estuary, 1 spring). **This leaves 86 potential stream sites with temperature.**

- I was able to retrieve temperature data from NWISdv for 65/86 sites. Of these 65 sites, 3 had no data after the NGWOS period started `2017-10-01`. 

- I looked in NWISuv for the remaining 24 (86-65+3) sites. I was able to retrieve data for 20/24 sites. 

- In total, I was able to retrieve data for **82/86 NGWOS stream sites**.

**Comment by aappling-usgs** [comment]
Wow, that's a huge bump up! Nice!

**Comment by limnoliver** [comment]
But now, just because I was able to get data doesn't mean 1) a site should be considered NGWOS (e.g., there was continuous data pre-NGWOS) or 2) a site has NGWOS data (after 2017-10-01).

Digging into this a bit more, here is all data from all 85 sites:


1.

**Comment by limnoliver** [comment]
Just because I was able to retrieve data does not mean 1) the site should be considered an NGWOS site in the case of the experiments (e.g., there were continuous data pre-NGWOS) or 2) the site has data in the NGWOS period (after 2017-10-01). Digging into these questions, here is all data from all 85 sites:

![image](https://user-images.githubusercontent.com/15788176/80108961-8db4e600-8542-11ea-8507-2ee75ee329b4.png)

1) There are 10 sites with data leading up to the NGWOS period (between 2013-10-01 and 2017-10-01). Of these, I feel confident in saying 6 of these should _not_ be considered "NGWOS" in the experiment since they had substantial data leading up to the NGWOS period.

![image](https://user-images.githubusercontent.com/15788176/80110016-d5883d00-8543-11ea-8433-35a34ee0fadb.png)

2) There were three sites (`c('01473470', '01477120', '01482100')`) where we found no data in the NGWOS period. 

The final tally, then, is 85-6-3 = **76 stream sites** that should be considered NGWOS sites in our experiment. Up next -- which of those sites get matched to our network?

**Comment by limnoliver** [comment]
Two of 76 sites (`01365100` and `01365550`) were outside of the DRB boundary. I verified that this is correct - one of these sites is the outlet of the aquaduct from Cannonsville. The other seems to be a natural inlet to Roundout reservoir. Both flow into Roundout Reservoir, and are east of the DRB boundary. 

PS -- thanks to the next gen station pages for easier sleuthing! 

![image](https://user-images.githubusercontent.com/15788176/81005023-ee7dd180-8e12-11ea-9bc3-2f716f30fa7a.png)

![image](https://user-images.githubusercontent.com/15788176/81006448-300f7c00-8e15-11ea-9919-70768ebfdc92.png)

**Comment by limnoliver** [comment]
Of the 74 river sites with data within the basin, 29 get filtered out either because of bird or fish distance. You can see from the figure below, some of these are clearly not on the modeling network, but others are being filtered out because they are too far away from the outlet (fish distance). Maybe we should revise that strategy, @aappling-usgs? One solution would be to keep everything that matches closely by bird distance, and when we're collapsing data to reach-day, we could take the value closest to the reach outlet by fish distance so we don't end up with a situation where we drop the only data we have for that reach?

![image](https://user-images.githubusercontent.com/15788176/81105248-4252ee00-8ed9-11ea-8d81-9b316e90f778.png)

**Comment by aappling-usgs** [comment]
I agree with easing up on the fish distance criterion.

Regarding collapsing, in the case of multiple data sources, this sounds a little bit like what we've struggled with for lakes - if we try to make use of several monitoring locations within the same reach, sometimes we'll end up with disagreements that make the collapsed-reach data pretty noisy. But if we don't make use of all the locations, we're leaving data on the table. I don't know what the answer is.

Regardless of whether we decide to merge multiple monitoring locations for a reach or to pick one location within the reach and go with it, I think we'd better prefer NGWOS data for the with-NGWOS-data scenarios. And we may need to do the collapsing all over again with NGWOS sites removed so that sites with multiple monitoring locations can take advantage of non-NGWOS data on days when an NGWOS data point would otherwise have been selected.

**Comment by limnoliver** [comment]
Thanks for the feedback, Alison. I don't think the collapsing issue is too great at NGWOS reaches -- I dug into this a bit when I first pulled NGWOS data (are NGWOS reaches monitored elsewhere, hence making the reach monitored pre-NGWOS or monitored in two locations? And the answer was mostly no.). And, I'm not sure how much of an issue it is generally, but will flag this for the next round of collapsing improvements. 

In terms of the comparison to lakes, I _think_ it will be less of an issue in streams given explicit connection between two sites on the same reach, and not having the potential for large differences in bathymetry/stratification across two sites. But, I can imagine multiple scenarios (e.g., tribs in between the two sites) where it might matter a lot.

**Comment by limnoliver** [comment]
If I really bump up the fish distance threshold (from 5km to 20 km), the DRB-matched sites go from 1373 to 2136. The NGWOS matched sites bumps up from 47 to 54 (53 + 1 manually rentered site from lower DRB - see #34 example).

**Comment by limnoliver** [comment]
In conclusion:

We went from 21 to 56 NGWOS reaches, from 10k to 19k NGWOS daily observations, and NGWOS making up 5% of the training data to 8% of the training data. 

Why didn't the % training double, like the number of reaches and daily observations did? Because I adjusted the fish distance criteria, which overall added a lot of data to non-NGWOS train data (202k to 224k).

**Comment by limnoliver** [comment]
And here are the 56 reaches in the NGWOS period (note - what's going on in 1449?):

![image](https://user-images.githubusercontent.com/15788176/81293184-81e11d80-9032-11ea-8d64-35d77c138fb1.png)
