### ISSUE TITLE
compare LST data with in situ observations

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/delaware-model-prep#30]
The EROS folks have provided land surface temperature data for three stream segments in the DRB. Now we get to compare that data to see how it compares with our in situ observations.

**Comment by jsadler2** [comment]
Here are the files that they shared with us
[ST_Analysis_for_WMA.pptx](https://github.com/USGS-R/delaware-model-prep/files/4540891/ST_Analysis_for_WMA.pptx)
[DRB_Landsat_ST.zip](https://github.com/USGS-R/delaware-model-prep/files/4540892/DRB_Landsat_ST.zip)

**Comment by jsadler2** [comment]
The three segments (from the presentation)
![image](https://user-images.githubusercontent.com/6943441/80397260-7bf17c80-887b-11ea-9866-40849d1a24b9.png)

**Comment by jsadler2** [comment]
Here's a geojson file of the USGS stations that also has the national segment ids (I had to upload it as a .txt file b/c GH doesn't support uploading json... so weird).
[usgs_stations_rs_instream.txt](https://github.com/USGS-R/delaware-model-prep/files/4540972/usgs_stations_rs_instream.txt)

**Comment by jsadler2** [comment]
What I've done so far
* Boxplots with the observations
* Note: one of the stations only has a few observations. Apparently I did not check the right thing when I was giving them points to look at.
    * Segment 1498: 2 days with oberservations/12 days of LST data
    * Segment 1568: 11/11
    * Segment 1718: 9/12
Total: 22/35

**Comment by jsadler2** [comment]
Example boxplot
![1568_20150215](https://user-images.githubusercontent.com/6943441/82230701-b639c100-98f1-11ea-964c-7062dfe5774c.png)

**Comment by jsadler2** [comment]
What should we do still?
* [ ] [Sam] Find the points closest to the observation points and compare that way
* [ ] [Sam - but Jeff wants to know!] Get the metadata for the 3 stations so we know where the measurements are being taken (where in the water column)
* [ ] [Jeff] Compare the bias between the three stations to see if it's consistent
* [ ] [Jeff] Have some maps of the spatial variation along the reach - visualize temp up and downstream
* [ ] [Jeff] Some are wider than others, would be nice to have some context for that when visualizing the data. 

Others?

**Comment by jsadler2** [comment]
[Link to presentation ](https://doimspp-my.sharepoint.com/:p:/g/personal/jsadler_usgs_gov/EQEyDQoMYeBOga5pTceWHxcBxqJ_FbjGLE7O3EZ8tGE0JA?email=soliver%40usgs.gov&e=LdTo7Y)where we can put our results.

**Comment by jsadler2** [comment]
The spatial variation is pretty interesting so far: 
![image](https://user-images.githubusercontent.com/6943441/82952566-d2cb9e00-9f6e-11ea-9c3b-80f93b848f32.png)

It's definitely important for this one that we are comparing the points next to the observation site b/c of that section that is actually over land.

**Comment by aappling-usgs** [comment]
@jsadler2 Should we call this issue done since you've given your presentation? Can create a new issue when we get a new round of data to work with.
