### ISSUE TITLE
ID reaches that are reservoirs

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/delaware-model-prep#31]
We want to identify which stream reaches in the DRB are actually reservoirs. I think the process should be:

1. Use a nationally-available reservoir or lake database, like the [NHD](https://nhd.usgs.gov/userGuide/Robohelpfiles/NHD_User_Guide/Feature_Catalog/Hydrography_Dataset/NHDPoint/Reservoir.htm) (it does specify reservoir and reservoir type) or [GRanD](https://sedac.ciesin.columbia.edu/data/set/grand-v1-dams-rev01) to get polygons. For now, I like the idea of GRanD because it is reservoir centric, and has volumes and other metadata associated with it. It was intended to capture reservoirs of >0.1km3, but notes there are smaller reservoirs when data were available.

2. Subset the reservoirs to those within our DRB footprint. Maintain these polygons in the pipeline - will be nice for plotting/mapping purposes.

2. Find all of the reaches in [our modeling network](https://github.com/USGS-R/delaware-model-prep/blob/master/1_network.yml#L45) that are within the polygon.

3. Create a dataframe of all network reaches with a field indicating whether the reach is a reservoir, and maintain some reservoir ID.

4. Create a dataframe of all reservoirs in the network that maintains the unique identifier and metadata (e.g., surface area, volume).

**Comment by limnoliver** [comment]
Where should this live? I think eventually we will do this at the national scale, or at least when we move to subbasins. For now, let's prototype this process in this pipeline, but eventually apply it at the national scale in the  [2WP-temp-observations](https://github.com/USGS-R/2wp-temp-observations) pipeline. 

With this pipeline, it should live either in the [1_network](https://github.com/USGS-R/delaware-model-prep/blob/master/1_network.yml) step or a new 1_reservoirs step.

**Comment by jzwart** [comment]
It seems like it could go in `1_network` since the reservoirs will be on the network.

**Comment by wdwatkins** [comment]
How important are partially overlapping reaches?  For instance here, the purple reach is mostly outside the reservoir:
![image](https://user-images.githubusercontent.com/13987349/80763729-093f0600-8af4-11ea-8e4b-549e33a2594e.png)

Most reaches actually intersect the reservoir boundaries rather than being contained within them.  So it would be simplest to just treat the purple reach as inside the reservoir.  It may be possible to compute the degree of overlap though.

**Comment by aappling-usgs** [comment]
Good Q. I could see treating any amount of overlap as 'reservoir' as a first cut, but it seems like a better solution to
> compute the degree of overlap though, and use some kind of threshold.

(i'd go with >=50% in reservoir == 'reservoir reach')

**Comment by limnoliver** [comment]
Thinking about your comment 

>  (actually this is the only reservoir in the DRB that contains any reaches)

On one hand, this is what I would expect since many of these are headwater reservoirs. On the other hand, I want to be sure we know which segments are downstream of reservoirs, even if the reach is just touching the reservoir. I like Alison's idea of 50%, but I'm wondering if we can also tag any reach that is any part within a reservoir polygon? (maybe >0 & < 50 == 'connected to reservoir' or some better name that I can't think of :))

**Comment by limnoliver** [comment]
I _think_ we can sort out later whether the reach is upstream or downstream of a reservoir.

**Comment by jzwart** [comment]
For model evaluation, we would want to know where along the reach the observations were collected to determine if it is a stream temperature vs. reservoir temperature. Maybe @limnoliver and @aappling-usgs already have this figured out.

**Comment by aappling-usgs** [comment]
I don't have anything already figured out. I wonder if we could intersect the observations directly with the reservoir polygons.

**Comment by limnoliver** [comment]
I think we will know this from the waterbody type in the metdata for the observations.

**Comment by limnoliver** [comment]
This is almost certainly true for NWIS data. I'd have to investigate for WQP data.

**Comment by wdwatkins** [comment]
I'm hoping to be able to calculate the percent overlap of a reach and the reservoir polygon.  I could just report to allow changing the threshold later.  

For sample locations, you could certainly intersect those with the reservoir polygons same as I've done with the stream reaches.
