### ISSUE TITLE
How to specify dates for "NGWOS period"

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/delaware-model-prep#33]
In our first experiment, we designated 2017-10-01 as the NGWOS period. Most sites came online after this date, with the exception of 4 of 76 NGWOS sites which came on earlier. What to do in these cases? If we include data prior to 2017-10-01 (say if a gage was installed 6 months before that date), it will likely make the NGWOS data seem artificially less important since the model received some info from the site. 

Choosing a dynamic NGWOS start date for each site is slightly more challenging and less concise to explain, but very doable. We would just look backwards in time to the most recent data gap to ID the start date.  This would drop all pre-NGWOS data from site `01474703`. Not sure what to do about `01467087` - there appears to be a winter gap early in 2018, so unclear if the data prior to that gap should be considered NGWOS, or the NGWOS portion came online later in 2018.

![image](https://user-images.githubusercontent.com/15788176/80968791-2dddfb00-8dde-11ea-9f77-61436595f897.png)

**Comment by aappling-usgs** [comment]
What do you think about preparing a very concise summary of the NWIS-visible data and our proposals for NGWOS start dates - maybe like the above but with site names as well as IDs, proposed start dates, and a plot for every NGWOS site (even including those that were listed in the spreadsheet but have no NWIS data?) - and then sending to Brian to see if he or a colleague of his could check through them and amend as needed? This seems like an important enough decision for any future NGWOS analyses that it'd be nice to know for sure that our assumptions and NGWOS's records agree. I don't think it should hold up a redo of our April analysis, but maybe such a doc could accompany the new results from that redo.

**Comment by limnoliver** [comment]
I like that idea, Alison. That will also help us communicate what data the experiment is considering.

**Comment by jread-usgs** [comment]
+1
