### ISSUE TITLE
error in building 9_collaborator_data

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/delaware-model-prep#39]
I'm getting an error when building `9_collaborator_data.yml` for target `network_subset.rds.ind`. I was building this to update with the latest NGWOS data. Also, I don't know why it's rebuilding this and some others (like `distance_matrix.*`). Should those have changed?
![image](https://user-images.githubusercontent.com/6943441/81444824-6a428b80-913d-11ea-9578-1bd3d1a34248.png)

**Comment by limnoliver** [comment]
`9_collaborator_data` built for me recently, I think this is related to missing coordinate references systems, but can't be sure. I'm going to close this since we've been able to build it.

**Comment by aappling-usgs** [comment]
I built it successfully yesterday.
