### ISSUE TITLE
Run PRMS-SNTemp 

### ISSUE THREAD

**Issue by jzwart** [USGS-R/delaware-model-prep#42]
Add in functions to run PRMS-SNTemp in the delaware-model-prep pipeline rather than in[ delaware-water-temp.](https://github.com/jzwart/delaware-water-temp) 

The targets needed to create uncalibrated SNTemp input and output are [here](https://github.com/jzwart/delaware-water-temp/blob/fb97bd2a9cab8c47b1d581951d9472249629217e/4_model_for_PGDL.yml#L33-L108). 

1. [get prms-sntemp model](https://github.com/jzwart/delaware-water-temp/blob/fb97bd2a9cab8c47b1d581951d9472249629217e/4_model_for_PGDL.yml#L33-L45) on your local machine (will be ~1-2 GB) 
2. [set important prms-sntemp configurations](https://github.com/jzwart/delaware-water-temp/blob/fb97bd2a9cab8c47b1d581951d9472249629217e/4_model_for_PGDL.yml#L47-L62), from the [configuration yaml ](https://github.com/jzwart/delaware-water-temp/blob/master/4_model_for_PGDL/cfg/uncal_settings.yml)
3. [run prms-sntemp](https://github.com/jzwart/delaware-water-temp/blob/fb97bd2a9cab8c47b1d581951d9472249629217e/4_model_for_PGDL.yml#L64-L71) (should take 1-2 mins to run from 1980-2019) 
4. [gather prms-sntemp output for RGCN ](https://github.com/jzwart/delaware-water-temp/blob/fb97bd2a9cab8c47b1d581951d9472249629217e/4_model_for_PGDL.yml#L73-L108)(this step takes the longest, ~10-20 mins depending on size of model output and internet bandwidth for pushing to GD) 

The main functions for running prms-sntemp are [here](https://github.com/jzwart/delaware-water-temp/blob/master/4_model/src/run_sntemp.R), getting prms-sntemp values are [here](https://github.com/jzwart/delaware-water-temp/blob/master/4_model/src/get_sntemp_values.R), and gathering output for RGCN are [here](https://github.com/jzwart/delaware-water-temp/blob/master/4_model_for_PGDL/src/data_for_pgdl.R). 

@hcorson-dosch plans on moving these functions and targets into the delaware-model-prep pipeline so we can run PRMS-SNTemp and produce output for RGCN all in this pipeline.

**Comment by aappling-usgs** [comment]
I'm taking off the "enhancement" label because I think this would be really useful to have in this pipeline.
