### ISSUE TITLE
Expanded surface temperature/in situ comparison (2015)

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/delaware-model-prep#51]
Comparing in situ temperature data to the Landsat Surface Temperature product for calendar year 2015 in the DRB. We have data for two scenes that cover the vast majority of the reaches in the basin.
![image](https://user-images.githubusercontent.com/6943441/87462574-c8746a80-c5d5-11ea-8c68-6505360e24c4.png)

**Comment by jsadler2** [comment]
We need to 
- [ ] add comparison with sntemp output
- [ ] add comparison with pgdl output
- [ ] incorporate reported uncertainty in the ST when doing comparison

**Comment by jsadler2** [comment]
I've been thinking through this some regarding the data format. I think what we will want is a table with these columns:

| date | usgs_station_id | in situ observation | average_ST | closest_ST | pgdl estimate | sntemp estimate|
| --- | --- | --- | --- | --- |--- | --- |
| ... | ... | ... | ... | ... | ... | ... |

**Comment by jsadler2** [comment]
@limnoliver  - I can start this file if you agree with the data format.

**Comment by limnoliver** [comment]
Oops, sorry I missed this Jeff. Yes, I think this is the _final_ table we'll want to end up with, right? In between there will be a long ST table with `date`, `usgs_station_id`, `st_lat`, `st_long`, `st_value`, `st_error`, right?

**Comment by jsadler2** [comment]
No problem. Yep. I made that table and a segment-wise table so far. So now I have two tables.

1. A  long table with all of the ST data

| X        | Y |       long        | lat  | seg_id_nat       | date  | st  | stqa |
| --- | --- | --- | --- | --- | --- | --- | --- |
| ... | ... | ... | ... | ... | ... | ... | ... |
2. A much shorter table with the ST data summarized by segment along with `sntemp`, `in situ`, and `pgdl` values.

| seg_id_nat  | date | sntemp  | in_situ  | st |  stqa  | pgdl |
| --- | --- | --- | --- | --- | --- | --- |
| ... | ... | ... | ... | ... | ... | ... |

**Comment by jsadler2** [comment]
Are you are still good finding the closest ST points to the USGS gauges and making that comparison? I think you will want the long table for that. I'm not sure if it makes sense to have the segment-level comparison (pgdl and sntemp) with that as well.

**Comment by limnoliver** [comment]
Yes. And yep, I think you're right. Makes sense to have a collapsed version of the ST data for this comparison.

**Comment by limnoliver** [comment]
Ok and just to be clear, are you pulling all of the data to populate these two tables? Did the lat/long come with seg_id_nat or do you have to make those matches?

**Comment by limnoliver** [comment]
Ok - just saw you sent the long table. Great! I will generate closest points.

**Comment by jsadler2** [comment]
The ST data was broken out by seg_id_nat, one file per seg_id_nat. I am trusting that they didn't do anything to mess up the Lat/Lon so I just matched on the seg_id_nat and didn't match on Lat/Lon. Does that answer your question?

**Comment by limnoliver** [comment]
Yep! Thanks.
