### ISSUE TITLE
upstream attribute aggregation difference in drainage area

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/delaware-model-prep#8]
aggregate upstream attributes

**Comment by jsadler2** [comment]
I have done a first cut of this. With averaging each of the 36 attributes being averaged except `hru_area`

**Comment by jsadler2** [comment]
I am getting a slight disparity between my aggregation of the `hru_area` and the `MAX_CUMDRAINAG` in the `highly_observed_sites.csv` table:
            
|seg_id_nat | MAX_CUMDRAINAG   |  hru_area|
|---|---|---|
|1586               |113.600   |113.601907|
|2277               |115.534   |115.532920|
|2013               |116.864   |133.652066|
|2014               |118.856   |135.643820|
|1703               |133.721   |133.724101|
|2297               |147.979   |147.980779|
|2281               |148.372   |158.987960|
|1588               |152.012   |152.015710|
|2332               |181.979   |181.979615|
|1645               |183.309   |183.309624|
|1683               |220.291   |227.927604|
|2012               |232.155   |232.159038|
|1697               |249.519   |249.524405|
|3570               |295.285   |295.287384|
|1684               |308.386   |311.611727|
|1641               |446.141   |446.144081|
|2333               |462.506   |462.508876|
|1647               |523.705   |523.700760|
|1457               |630.571   |630.572413|
|2037               |720.558   |745.197556|
|1695               |740.605   |751.391683|
|1601               |746.596   |746.612238|
|2046               |799.545   |824.185545|
|1566              |1183.972  |1183.982120|
|1450              |1185.011  |1185.010248|
|1565              |1537.790  |1544.058087|
|1571              |1676.390  |1682.659854|
|1462              |2030.644  |2030.644444|
|1718              |3508.087  |3525.804696|
|1573              |4112.176  |4118.450051|
|2320              |4551.260  |4561.887332|
|1578              |4721.712  |4727.986511|
|2338              |4872.529  |4883.153532|
|1568              |5229.466  |5242.925858|

**Comment by jzwart** [comment]
how are each calculated? I was going to suggest rounding error but some are pretty different

**Comment by jsadler2** [comment]
That's a good question. I'm not actually sure where the `MAX_CUMDRANAG` is coming from. The `hru_area` is coming from this https://www.sciencebase.gov/catalog/item/537a59ece4b0efa8af081526 and then each of the upstream `hru_areas` are added to the given reach's `hru_area`

**Comment by jsadler2** [comment]
Maybe it's not something to worry about, but I just wanted to make sure it's documented.

**Comment by jsadler2** [comment]
FYI @aappling-usgs

**Comment by limnoliver** [comment]
`MAX_CUMDRANAG` is from the metadata that comes with the national geofabric.

**Comment by aappling-usgs** [comment]
This is good to have documented, agreed. Three sites have 5-10% differences, and the others are more like 1% or less, so I'm not feeling too concerned about it...but still good to know.

It looks like a rounding/precision issue to me, recognizing that precision gets even messier when you're talking about polygons rather than simple numbers. And maybe there's greater discrepancy where the oNHM pour points don't land exactly at the ends of NHD reaches?

**Comment by jsadler2** [comment]
Ahh. Okay. Thanks, @limnoliver. I wonder they are different numbers though. I would think that they both come from the NHD. Maybe it's b/c the `hru_area` is actually the area of the basin and that gets counted differently than the drainage area of a stream reach? It's also weird that some of them are the same and some are quite different.
