### ISSUE TITLE
add zarr targets

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/delaware-model-prep#88]
I've been using zarr datasets for my DL models. I convert `obs_flow_full.csv`, `obs_temp_full.csv` and `uncal_sntemp_input_output.feather` into zarr. I have been doing this in a manual way, but it'd be good to get it formalized in the pipeline.

**Comment by jzwart** [comment]
I was thinking about converting the output for PRMS-SNTemp into NetCDF in this pipeline - https://code.usgs.gov/wma/wp/run-prms-sntemp 
Should we commit to zarr vs. NetCDF or is it easy to convert between the two that it shouldn't matter?

**Comment by jsadler2** [comment]
It's very easy to convert between the two:
```python
import xarray as xr

ds = xr.open_dataset("myfile.nc")
ds.to_zarr("myfile")
```
and vice versa.

So I don't think we need to commit to Zarr.
