### ISSUE TITLE
Update temperature munge functions 

### ISSUE THREAD

**Issue by jzwart** [USGS-R/delaware-model-prep#91]
I ran `scmake('3_predictions/out/model_evaluation.csv')` and ran into an issue with the temperature observation [target](https://github.com/USGS-R/delaware-model-prep/blob/80614a01748883b880606d87927e6b6a0b641779/2_observations.yml#L80-L84): 
``` 
[ BUILD ] 2_observations/out/obs_temp_drb.rds.ind                                             |  munge_t...
Restoring previous version of 2_observations/out/obs_temp_drb.rds.ind
 Error: `distinct()` must use existing variables.
x `temp_degC` not found in `.data`. 
```
It looks like the temperature in data has changed to include mean/min/max but the temperature munge functions haven't been updated yet: 
```
dat <- readRDS(sc_retrieve('2_observations/out/all_drb_temp_obs.rds.ind', 'getters.yml'))
> dat
# A tibble: 548,881 x 7
   site_id       date                mean_temp_degC min_temp_degC max_temp_degC n_obs source 
   <chr>         <dttm>                       <dbl>         <dbl>         <dbl> <dbl> <chr>  
 1 USGS-01432160 1967-10-01 00:00:00             NA          13.5          15      NA nwis_dv
 2 USGS-01432160 1967-10-02 00:00:00             NA          12            15.5    NA nwis_dv
 3 USGS-01432160 1967-10-04 00:00:00             NA          17            22.5    NA nwis_dv
 4 USGS-01432160 1967-10-05 00:00:00             NA          18.5          22      NA nwis_dv
 5 USGS-01432160 1967-10-06 00:00:00             NA          16.5          19      NA nwis_dv
 6 USGS-01432160 1967-10-07 00:00:00             NA          14.5          16.5    NA nwis_dv
 7 USGS-01432160 1967-10-08 00:00:00             NA          14            14.5    NA nwis_dv
 8 USGS-01432160 1967-10-09 00:00:00             NA          14            15      NA nwis_dv
 9 USGS-01432160 1967-10-11 00:00:00             NA          13.5          14.5    NA nwis_dv
10 USGS-01432160 1967-10-12 00:00:00             NA          12            13.5    NA nwis_dv
# ... with 548,871 more rows
``` 
Temperature munge function [here](https://github.com/USGS-R/delaware-model-prep/blob/80614a01748883b880606d87927e6b6a0b641779/2_observations/src/data_munge_functions.R#L50-L54), which runs `distinct()` on old column names. While updating some PRMS functions and model comparisons in `3_predictions`, I can update the temperature munge functions as well, unless someone else is doing that.

**Comment by jzwart** [comment]
For the data munge, do we want to summarize duplicate sites and dates by the mean of the max and min temperatures or the max of the max temps and min of the min temps? 

e.g. of max of the max temps and min of the min temps 
```
drb_dat <- filter(dat, site_id %in% unique(sites$site_id)) %>%
    distinct(site_id, date, mean_temp_degC, .keep_all = TRUE) %>%
    group_by(site_id, date) %>%
    summarize(mean_temp_C = mean(mean_temp_degC),
              min_temp_C = min(min_temp_degC),
              max_temp_C = max(max_temp_degC)) %>%
    ungroup()
```
vs. mean of the max and min 
```
drb_dat <- filter(dat, site_id %in% unique(sites$site_id)) %>%
    distinct(site_id, date, mean_temp_degC, .keep_all = TRUE) %>%
    group_by(site_id, date) %>%
    summarize(mean_temp_C = mean(mean_temp_degC),
              min_temp_C = mean(min_temp_degC),
              max_temp_C = mean(max_temp_degC)) %>%
    ungroup()
```
I think maybe taking the max of `max_temp_degC` and min of `min_temp_degC` makes sense - it would more accurately represent the maximum or minimum temperature of the observations for that site-date

**Comment by limnoliver** [comment]
Thanks for these changes, Jake, yes, I agree that taking the min of min and max of max makes sense.
